source 'https://rubygems.org'

gem 'tire'
gem 'sinatra'
gem 'poncho'
gem 'nokogiri'
gem 'sprockets'
gem 'sprockets-sass'
gem 'compass'
gem 'modular-scale'
gem 'haml'

gem 'capistrano', '>=2.15.4'
gem 'unicorn'
gem 'rake'
gem 'sprockets-helpers'
gem 'therubyracer'
gem 'uglifier'
gem 'sinatra-asset-pipeline'